export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_ERROR = "GET_BOOKS_ERROR";

export const POST_BOOKS_REQUEST = "POST_BOOKS_REQUEST";
export const POST_BOOKS_SUCCESS = "POST_BOOKS_SUCCESS";
export const POST_BOOKS_ERROR = "POST_BOOKS_ERROR";

export const EDIT_BOOKS_REQUEST = "EDIT_BOOKS_REQUEST";
export const EDIT_BOOKS_SUCCESS = "EDIT_BOOKS_SUCCESS";
export const EDIT_BOOKS_ERROR = "EDIT_BOOKS_ERROR";

export const DELETE_BOOKS_REQUEST = "DELETE_BOOKS_REQUEST";
export const DELETE_BOOKS_SUCCESS = "DELETE_BOOKS_SUCCESS";
export const DELETE_BOOKS_ERROR = "DELETE_BOOKS_ERROR";